version: '3'
services:
  my-app:
    image: vaibhavdawane/my-node-app:latest
    ports:
     - 3000:3000
     
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js # mounting js script to the container entrypoint
      # after container starts, it will execute the entry point script automatically
     - mongo-data:/data/db # first name of volume, and then path to where mongodb store data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local
